import type { Data, Match, MatchSet, Rules, Standing } from './types';
export const active=<T extends {deletedAt?:string}>(items:T[])=>items.filter(x=>!x.deletedAt);
export function setWins(sets:MatchSet[]) { return sets.reduce((s,v)=>({a:s.a+(v.a>v.b?1:0),b:s.b+(v.b>v.a?1:0)}),{a:0,b:0}); }
export function validateSets(sets:MatchSet[]):string|undefined {
 if(sets.length<2||sets.length>3)return 'Complete two or three sets before finishing.';
 for(let i=0;i<sets.length;i++) {const {a,b}=sets[i];if(!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0)return 'Scores must be whole numbers of zero or more.';const high=Math.max(a,b),low=Math.min(a,b);if(i<2?!((high===6&&low<=4)||(high===7&&(low===5||low===6))):!(high>=10&&high-low>=2&&(high===10||high-low===2)))return `Set ${i+1}: ${i<2?'use a valid set score (6–0 to 6–4, 7–5 or 7–6).':'the deciding tiebreak is first to 10, win by two.'}`;}
 const first=setWins(sets.slice(0,2));if((first.a===2||first.b===2)&&sets.length===3)return 'A third set is not played after a 2–0 result.';const result=setWins(sets);if(result.a!==2&&result.b!==2)return 'A team must win two sets.';
}
function points(r:Rules,won:boolean,setsWon:number,setsLost:number){return r.split?(won?(setsLost===0?r.win20:r.win21):(setsWon===0?r.loss02:r.loss12)):(won?r.win:r.loss);}
export function visibleMatches(d:Data):Match[]{const events=new Set(active(d.events).map(x=>x.id)),cats=new Set(active(d.categories).map(x=>x.id)),teams=new Set(active(d.teams).map(x=>x.id)),groups=new Set(active(d.groups).map(x=>x.id));return active(d.matches).filter(m=>events.has(m.eventId)&&cats.has(m.categoryId)&&(!m.groupId||groups.has(m.groupId))&&(!m.teamAId||teams.has(m.teamAId))&&(!m.teamBId||teams.has(m.teamBId)));}
export function standings(d:Data,groupId:string):Standing[]{
 const group=active(d.groups).find(g=>g.id===groupId);if(!group)return [];const category=active(d.categories).find(c=>c.id===group.categoryId);if(!category||!active(d.events).some(e=>e.id===group.eventId))return [];
 const rows:Standing[]=active(d.teams).filter(t=>t.groupId===groupId&&t.categoryId===group.categoryId).map(team=>({team,MP:0,W:0,L:0,SF:0,SA:0,SD:0,GF:0,GA:0,GD:0,PTS:0,H2H:0,tied:false}));const byId=new Map(rows.map(r=>[r.team.id,r]));
 const matches=visibleMatches(d).filter(m=>m.groupId===groupId&&m.stage==='GROUP'&&m.status==='FINISHED'&&byId.has(m.teamAId)&&byId.has(m.teamBId));
 for(const m of matches){const s=setWins(m.sets);for(const [id,isA] of [[m.teamAId,true],[m.teamBId,false]] as const){const row=byId.get(id)!;const sf=isA?s.a:s.b,sa=isA?s.b:s.a,won=sf>sa;row.MP++;row.W+=won?1:0;row.L+=won?0:1;row.SF+=sf;row.SA+=sa;row.GF+=m.sets.reduce((n,v)=>n+(isA?v.a:v.b),0);row.GA+=m.sets.reduce((n,v)=>n+(isA?v.b:v.a),0);row.PTS+=points(category.rules,won,sf,sa);}}
 for(const row of rows){row.SD=row.SF-row.SA;row.GD=row.GF-row.GA;const tiedIds=new Set(rows.filter(r=>r.PTS===row.PTS).map(r=>r.team.id));for(const m of matches.filter(m=>tiedIds.has(m.teamAId)&&tiedIds.has(m.teamBId)&&(m.teamAId===row.team.id||m.teamBId===row.team.id))){const s=setWins(m.sets),a=m.teamAId===row.team.id;row.H2H+=points(category.rules,a?s.a>s.b:s.b>s.a,a?s.a:s.b,a?s.b:s.a);}}
 const compare=(a:Standing,b:Standing)=>{for(const key of category.rules.tieBreak){if(a[key]!==b[key])return b[key]-a[key];}return 0;};rows.sort(compare);rows.forEach((r,i)=>{r.tied=r.MP>0&&((i>0&&compare(r,rows[i-1])===0)||(i<rows.length-1&&compare(r,rows[i+1])===0));});return rows;
}
export function validateMatch(d:Data,m:Match){const cat=active(d.categories).find(c=>c.id===m.categoryId&&c.eventId===m.eventId);if(!cat)throw Error('Choose a category in this event.');if(m.teamAId&&m.teamAId===m.teamBId)throw Error('A team cannot play itself.');if(m.stage==='GROUP'&&(!m.groupId||!m.teamAId||!m.teamBId))throw Error('Group matches need a group and two teams.');if(m.groupId&&!active(d.groups).some(g=>g.id===m.groupId&&g.categoryId===m.categoryId))throw Error('The group must belong to the selected category.');for(const id of [m.teamAId,m.teamBId].filter(Boolean)){const t=active(d.teams).find(t=>t.id===id);if(!t||t.categoryId!==m.categoryId||t.eventId!==m.eventId)throw Error('Both teams must belong to this category.');if(m.stage==='GROUP'&&t.groupId!==m.groupId)throw Error('Both teams must belong to the selected group.');}if(m.courtId&&!active(d.courts).some(c=>c.id===m.courtId&&c.eventId===m.eventId&&c.active))throw Error('Choose an active court in this event.');}
export function scheduleWarnings(d:Data,m:Match){if(!m.scheduledAt)return [];const same=visibleMatches(d).filter(x=>x.id!==m.id&&x.eventId===m.eventId&&x.scheduledAt&&x.status!=='CANCELLED'&&Math.abs(Date.parse(x.scheduledAt)-Date.parse(m.scheduledAt!))<3600000);return [...(m.courtId&&same.some(x=>x.courtId===m.courtId)?['This court has another match within 60 minutes.']:[]),...(same.some(x=>[x.teamAId,x.teamBId].some(t=>!!t&&[m.teamAId,m.teamBId].includes(t)))?['A team has another match within 60 minutes.']:[])];}
export function descendants(d:Data,id:string){const ids:string[]=[];let m=d.matches.find(m=>m.id===id);while(m?.nextMatchId&&!ids.includes(m.nextMatchId)){ids.push(m.nextMatchId);m=d.matches.find(x=>x.id===m!.nextMatchId);}return ids;}
export function clearProgression(d:Data,id:string){const visited=new Set<string>();let source=d.matches.find(m=>m.id===id);while(source?.nextMatchId&&!visited.has(source.nextMatchId)){visited.add(source.nextMatchId);const next=d.matches.find(m=>m.id===source!.nextMatchId);if(!next)break;if(source.nextSlot==='A')next.teamAId='';else next.teamBId='';next.winnerId=undefined;next.sets=[];next.status='SCHEDULED';source=next;}}
export function updateScore(d:Data,id:string,sets:MatchSet[],status:Match['status']){const m=d.matches.find(x=>x.id===id);if(!m)throw Error('Match not found.');if(m.deletedAt)throw Error('Restore this match first.');if(status==='FINISHED'){validateMatch(d,m);if(!m.teamAId||!m.teamBId)throw Error('Both participants must be known.');const error=validateSets(sets);if(error)throw Error(error);}else if(sets.some(s=>!Number.isInteger(s.a)||!Number.isInteger(s.b)||s.a<0||s.b<0))throw Error('Scores must be non-negative whole numbers.');clearProgression(d,id);m.sets=sets;m.status=status;m.winnerId=status==='FINISHED'?(setWins(sets).a===2?m.teamAId:m.teamBId):undefined;if(m.winnerId&&m.nextMatchId){const next=d.matches.find(x=>x.id===m.nextMatchId);if(next){if(m.nextSlot==='A')next.teamAId=m.winnerId;else next.teamBId=m.winnerId;}}return m;}
