import { type Data, type Match, type MatchSet, type Rules, type Standing } from './types';
export const active=<T extends {deletedAt?:string}>(items:T[])=>items.filter(x=>!x.deletedAt);
export function setWins(sets:MatchSet[]) { return sets.reduce((s,v)=>({a:s.a+(v.a>v.b?1:0),b:s.b+(v.b>v.a?1:0)}),{a:0,b:0}); }
export function validateSets(sets:MatchSet[],lineupCategory?:Match['lineupCategory']):string|undefined {
 if(lineupCategory==='EXTRA'&&sets.length!==1)return 'Complete one set for the Extra match.';
 if(lineupCategory!=='EXTRA'&&(sets.length<2||sets.length>3))return 'Complete two or three sets before finishing.';
 for(let i=0;i<sets.length;i++) {const {a,b}=sets[i];if(!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0)return 'Scores must be whole numbers of zero or more.';const high=Math.max(a,b),low=Math.min(a,b);if(i<2?!((high===6&&low<=4)||(high===7&&(low===5||low===6))):!(high>=10&&high-low>=2&&(high===10||high-low===2)))return `Set ${i+1}: ${i<2?'use a valid set score (6–0 to 6–4, 7–5 or 7–6).':'the deciding tiebreak is first to 10, win by two.'}`;}
 if(lineupCategory==='EXTRA')return;
 const first=setWins(sets.slice(0,2));if((first.a===2||first.b===2)&&sets.length===3)return 'A third set is not played after a 2–0 result.';const result=setWins(sets);if(result.a!==2&&result.b!==2)return 'A team must win two sets.';
}
function points(r:Rules,won:boolean,setsWon:number,setsLost:number){return r.split?(won?(setsLost===0?r.win20:r.win21):(setsWon===0?r.loss02:r.loss12)):(won?r.win:r.loss);}
export function visibleMatches(d:Data):Match[]{const events=new Set(active(d.events).map(x=>x.id)),cats=new Set(active(d.categories).map(x=>x.id)),teams=new Set(active(d.teams).map(x=>x.id)),groups=new Set(active(d.groups).map(x=>x.id));return active(d.matches).filter(m=>events.has(m.eventId)&&cats.has(m.categoryId)&&(!m.groupId||groups.has(m.groupId))&&(!m.teamAId||teams.has(m.teamAId))&&(!m.teamBId||teams.has(m.teamBId)));}
const matchWinner=(match:Match)=>{const score=setWins(match.sets);return score.a===score.b?undefined:score.a>score.b?match.teamAId:match.teamBId;};
function encounterMatches(d:Data,match:Match){return active(d.matches).filter(item=>item.eventId===match.eventId&&item.categoryId===match.categoryId&&item.groupId===match.groupId&&item.lineupCategory&&[item.teamAId,item.teamBId].includes(match.teamAId)&&[item.teamAId,item.teamBId].includes(match.teamBId));}
export function extraRequired(d:Data,match:Match){if(!match.groupId||!match.lineupCategory)return false;const lineups=encounterMatches(d,match);const beginner=lineups.find(item=>item.lineupCategory==='BEGINNER'),bronze=lineups.find(item=>item.lineupCategory==='BRONZE');if(!beginner||!bronze||beginner.status!=='FINISHED'||bronze.status!=='FINISHED')return false;const beginnerWinner=matchWinner(beginner),bronzeWinner=matchWinner(bronze);return !!beginnerWinner&&!!bronzeWinner&&beginnerWinner!==bronzeWinner;}
function syncExtraFlow(d:Data,match:Match){if(!match.groupId||!['BEGINNER','BRONZE'].includes(match.lineupCategory||''))return;const extra=encounterMatches(d,match).find(item=>item.lineupCategory==='EXTRA');if(!extra||extra.status==='FINISHED')return;if(extraRequired(d,match)){extra.status='SCHEDULED';return;}const regular=encounterMatches(d,match).filter(item=>item.lineupCategory!=='EXTRA');const complete=regular.length===2&&regular.every(item=>item.status==='FINISHED');extra.status=complete?'CANCELLED':'POSTPONED';extra.sets=[];extra.winnerId=undefined;}
export function standings(d:Data,groupId:string):Standing[]{
 const group=active(d.groups).find(g=>g.id===groupId);if(!group)return [];const category=active(d.categories).find(c=>c.id===group.categoryId);if(!category||!active(d.events).some(e=>e.id===group.eventId))return [];
 const rows:Standing[]=active(d.teams).filter(t=>t.groupId===groupId&&t.categoryId===group.categoryId).map(team=>({team,MP:0,W:0,L:0,SF:0,SA:0,SD:0,GF:0,GA:0,GD:0,PTS:0,H2H:0,tied:false}));const byId=new Map(rows.map(r=>[r.team.id,r]));
 const matches=visibleMatches(d).filter(m=>m.groupId===groupId&&m.stage==='GROUP'&&byId.has(m.teamAId)&&byId.has(m.teamBId));
 type Result={teamAId:string;teamBId:string;sfA:number;sfB:number;gfA:number;gfB:number};
 const results:Result[]=[];
 const encounters=new Map<string,Match[]>();
 for(const m of matches.filter(m=>m.lineupCategory)){const key=[m.teamAId,m.teamBId].sort().join(':');encounters.set(key,[...(encounters.get(key)||[]),m]);}
 for(const m of matches.filter(m=>!m.lineupCategory&&m.status==='FINISHED'&&!encounters.has([m.teamAId,m.teamBId].sort().join(':')))){const s=setWins(m.sets);results.push({teamAId:m.teamAId,teamBId:m.teamBId,sfA:s.a,sfB:s.b,gfA:m.sets.reduce((n,v)=>n+v.a,0),gfB:m.sets.reduce((n,v)=>n+v.b,0)});}
 for(const encounter of encounters.values()){
  const beginner=encounter.find(m=>m.lineupCategory==='BEGINNER'),bronze=encounter.find(m=>m.lineupCategory==='BRONZE'),extra=encounter.find(m=>m.lineupCategory==='EXTRA');
  if(!beginner||!bronze||beginner.status!=='FINISHED'||bronze.status!=='FINISHED')continue;
  const beginnerWinner=matchWinner(beginner),bronzeWinner=matchWinner(bronze);if(!beginnerWinner||!bronzeWinner)continue;
  const teamAId=beginner.teamAId,teamBId=beginner.teamBId;const decided=beginnerWinner===bronzeWinner?beginnerWinner:extra?.status==='FINISHED'?matchWinner(extra):undefined;if(!decided)continue;
  const counted=beginnerWinner===bronzeWinner?[beginner,bronze]:[beginner,bronze,extra!];const score=beginnerWinner===bronzeWinner?2:1;let gfA=0,gfB=0;
  for(const m of counted){const same=m.teamAId===teamAId;gfA+=m.sets.reduce((n,v)=>n+(same?v.a:v.b),0);gfB+=m.sets.reduce((n,v)=>n+(same?v.b:v.a),0);}
  results.push({teamAId,teamBId,sfA:decided===teamAId?score:0,sfB:decided===teamBId?score:0,gfA,gfB});
 }
 for(const result of results){for(const [id,isA] of [[result.teamAId,true],[result.teamBId,false]] as const){const row=byId.get(id)!;const sf=isA?result.sfA:result.sfB,sa=isA?result.sfB:result.sfA,won=sf>sa;row.MP++;row.W+=won?1:0;row.L+=won?0:1;row.SF+=sf;row.SA+=sa;row.GF+=isA?result.gfA:result.gfB;row.GA+=isA?result.gfB:result.gfA;row.PTS+=points(category.rules,won,sf,sa);}}
 for(const row of rows){row.SD=row.SF-row.SA;row.GD=row.GF-row.GA;const tiedIds=new Set(rows.filter(r=>r.PTS===row.PTS).map(r=>r.team.id));for(const result of results.filter(result=>tiedIds.has(result.teamAId)&&tiedIds.has(result.teamBId)&&(result.teamAId===row.team.id||result.teamBId===row.team.id))){const a=result.teamAId===row.team.id;row.H2H+=points(category.rules,a?result.sfA>result.sfB:result.sfB>result.sfA,a?result.sfA:result.sfB,a?result.sfB:result.sfA);}}
 const compare=(a:Standing,b:Standing)=>{const aUnplayed=a.MP===0,bUnplayed=b.MP===0;if(aUnplayed!==bUnplayed)return aUnplayed?1:-1;for(const key of category.rules.tieBreak){if(a[key]!==b[key])return key==='L'?a.L-b.L:b[key]-a[key];}return 0;};rows.sort(compare);rows.forEach((r,i)=>{r.tied=r.MP>0&&((i>0&&compare(r,rows[i-1])===0)||(i<rows.length-1&&compare(r,rows[i+1])===0));});return rows;
}
export function validateMatch(d:Data,m:Match){const cat=active(d.categories).find(c=>c.id===m.categoryId&&c.eventId===m.eventId);if(!cat)throw Error('Choose a category in this event.');if(m.teamAId&&m.teamAId===m.teamBId)throw Error('A team cannot play itself.');if(m.stage==='GROUP'&&(!m.groupId||!m.teamAId||!m.teamBId))throw Error('Group matches need a group and two teams.');if(m.groupId&&!active(d.groups).some(g=>g.id===m.groupId&&g.categoryId===m.categoryId))throw Error('The group must belong to the selected category.');for(const id of [m.teamAId,m.teamBId].filter(Boolean)){const t=active(d.teams).find(t=>t.id===id);if(!t||t.categoryId!==m.categoryId||t.eventId!==m.eventId)throw Error('Both teams must belong to this category.');if(m.stage==='GROUP'&&t.groupId!==m.groupId)throw Error('Both teams must belong to the selected group.');}if(m.lineupCategory&&active(d.matches).some(x=>x.id!==m.id&&x.groupId===m.groupId&&x.lineupCategory===m.lineupCategory&&[x.teamAId,x.teamBId].includes(m.teamAId)&&[x.teamAId,x.teamBId].includes(m.teamBId)))throw Error(`A ${m.lineupCategory.toLowerCase()} match already exists for these teams.`);if(m.courtId&&!active(d.courts).some(c=>c.id===m.courtId&&c.eventId===m.eventId&&c.active))throw Error('Choose an active court in this event.');}
export function scheduleWarnings(d:Data,m:Match){if(!m.scheduledAt)return [];const same=visibleMatches(d).filter(x=>x.id!==m.id&&x.eventId===m.eventId&&x.scheduledAt&&x.status!=='CANCELLED'&&Math.abs(Date.parse(x.scheduledAt)-Date.parse(m.scheduledAt!))<3600000);return [...(m.courtId&&same.some(x=>x.courtId===m.courtId)?['This court has another match within 60 minutes.']:[]),...(same.some(x=>[x.teamAId,x.teamBId].some(t=>!!t&&[m.teamAId,m.teamBId].includes(t)))?['A team has another match within 60 minutes.']:[])];}
export function descendants(d:Data,id:string){const ids:string[]=[];let m=d.matches.find(m=>m.id===id);while(m?.nextMatchId&&!ids.includes(m.nextMatchId)){ids.push(m.nextMatchId);m=d.matches.find(x=>x.id===m!.nextMatchId);}return ids;}
export function clearProgression(d:Data,id:string){const visited=new Set<string>();let source=d.matches.find(m=>m.id===id);while(source?.nextMatchId&&!visited.has(source.nextMatchId)){visited.add(source.nextMatchId);const next=d.matches.find(m=>m.id===source!.nextMatchId);if(!next)break;if(source.nextSlot==='A')next.teamAId='';else next.teamBId='';next.winnerId=undefined;next.sets=[];next.status='SCHEDULED';source=next;}}
export function updateScore(d:Data,id:string,sets:MatchSet[],status:Match['status']){const m=d.matches.find(x=>x.id===id);if(!m)throw Error('Match not found.');if(m.deletedAt)throw Error('Restore this match first.');if(m.lineupCategory==='EXTRA'&&status!=='SCHEDULED'&&!extraRequired(d,m))throw Error('Extra is available only after Beginner and Bronze are finished one win each.');if(status==='FINISHED'){validateMatch(d,m);if(!m.teamAId||!m.teamBId)throw Error('Both participants must be known.');const error=validateSets(sets,m.lineupCategory);if(error)throw Error(error);}else if(sets.some(s=>!Number.isInteger(s.a)||!Number.isInteger(s.b)||s.a<0||s.b<0))throw Error('Scores must be non-negative whole numbers.');clearProgression(d,id);m.sets=sets;m.status=status;const wins=setWins(sets);m.winnerId=status==='FINISHED'?(wins.a>wins.b?m.teamAId:m.teamBId):undefined;syncExtraFlow(d,m);if(m.winnerId&&m.nextMatchId){const next=d.matches.find(x=>x.id===m.nextMatchId);if(next){if(m.nextSlot==='A')next.teamAId=m.winnerId;else next.teamBId=m.winnerId;}}return m;}
