'use client';
import { create } from 'zustand';
import { persist, createJSONStorage, type StateStorage } from 'zustand/middleware';
import { z } from 'zod';
import { createSeed } from './seed';
import { active, clearProgression, updateScore, validateMatch } from './engine';
import { LINEUP_CATEGORIES, type Data, type Entity, type Match, type MatchSet, type RecordItem, type TournamentRepository, type SessionAdapter } from './types';
const id=()=>crypto.randomUUID();
const base=z.object({id:z.string(),name:z.string(),deletedAt:z.string().optional()}).passthrough();
const scoped=base.extend({eventId:z.string()});
const persistedData=z.object({events:z.array(base.extend({slug:z.string(),startDate:z.string(),endDate:z.string(),status:z.enum(['UPCOMING','ONGOING','FINISHED']),venue:z.string(),organizer:z.string(),description:z.string()})),categories:z.array(scoped.extend({rules:z.object({win:z.number(),loss:z.number(),split:z.boolean(),win20:z.number(),win21:z.number(),loss12:z.number(),loss02:z.number(),tieBreak:z.array(z.enum(['PTS','H2H','SD','GD','GF'])).min(1),qualifiersPerGroup:z.number().int().min(1).max(4).optional(),bracketSize:z.union([z.literal(2),z.literal(4),z.literal(8)]).optional()})})),groups:z.array(scoped.extend({categoryId:z.string()})),teams:z.array(scoped.extend({categoryId:z.string()})),players:z.array(scoped.extend({teamId:z.string()})),courts:z.array(scoped.extend({active:z.boolean(),sortOrder:z.number()})),matches:z.array(scoped.extend({categoryId:z.string(),teamAId:z.string(),teamBId:z.string(),lineupCategory:z.enum(LINEUP_CATEGORIES).optional(),stage:z.enum(['GROUP','QUARTER_FINAL','SEMI_FINAL','FINAL','OTHER']),status:z.enum(['SCHEDULED','LIVE','FINISHED','POSTPONED','CANCELLED']),sets:z.array(z.object({a:z.number(),b:z.number()}))})),users:z.array(scoped.extend({email:z.string(),role:z.enum(['SUPER_ADMIN','EVENT_ADMIN','SCOREKEEPER']),active:z.boolean()})),audits:z.array(base.extend({userId:z.string(),userName:z.string(),action:z.string(),entity:z.string(),entityId:z.string(),timestamp:z.string()}))});
let storageIssue='';
const safeStorage:StateStorage={getItem(name){try{return localStorage.getItem(name);}catch{storageIssue='Browser storage is unavailable. Changes will last until this page closes.';return null;}},setItem(name,value){try{localStorage.setItem(name,value);}catch{queueMicrotask(()=>useTournament.setState({storageError:'Your latest changes could not be saved to this browser. Remove large images or reset demo data, then try again.'}));}},removeItem(name){try{localStorage.removeItem(name);}catch{storageIssue='Browser storage could not be cleared.';}}};
type RemotePayload={action:'save';entity:Entity;record:RecordItem}|{action:'score';id:string;sets:MatchSet[];status:Match['status']}|{action:'delete';entity:Entity;id:string;permanent:boolean}|{action:'restore';entity:Entity;id:string};
type RemoteResponse={data:Data;userId:string|null;error?:string};
async function refreshRemote(){const response=await fetch('/api/tournament',{cache:'no-store'});const payload=await response.json() as RemoteResponse;if(!response.ok)throw Error(payload.error||'Could not load tournament data.');useTournament.setState({data:payload.data,userId:payload.userId,storageError:''});}
async function sendRemote(payload:RemotePayload){try{const response=await fetch('/api/tournament',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as RemoteResponse;if(!response.ok)throw Error(result.error||'Could not save this change.');useTournament.setState({data:result.data,userId:result.userId,storageError:''});}catch(error){const message=(error as Error).message||'Could not save the latest change to Supabase.';useTournament.setState({storageError:message});throw new Error(message);}}
function queueRemote(payload:RemotePayload){if(process.env.NODE_ENV==='test')return Promise.resolve();const request=sendRemote(payload);void request.catch(()=>undefined);return request;}
interface Store extends TournamentRepository,SessionAdapter { hydrated:boolean; storageError:string; hydrate:()=>Promise<void>; refresh:()=>Promise<void>; reset:()=>void; dismissStorageError:()=>void; score:(id:string,sets:MatchSet[],status:Match['status'])=>void; generate:(groupId:string)=>number; }
function authorize(d:Data,userId:string|null,entity:Entity,record?:RecordItem,scoreOnly=false){const user=active(d.users).find(u=>u.id===userId&&u.active);if(!user)throw Error('Choose a demo account to continue.');if(user.role==='SUPER_ADMIN')return user;if(entity==='users'||entity==='events'&&!record)throw Error('Only a Super Admin can manage this resource.');if(user.role==='SCOREKEEPER'&&(!scoreOnly||entity!=='matches'))throw Error('Scorekeepers can only update match scores.');const eventId=record&&('eventId'in record?record.eventId:record.id);if(eventId!==user.eventId)throw Error('This event is not assigned to your account.');return user;}
function log(d:Data,userId:string|null,action:string,entity:Entity,record:RecordItem,before?:RecordItem){const user=d.users.find(u=>u.id===userId);const format=(v:RecordItem)=>Object.entries(v).filter(([key])=>!['logo','banner','photo','rules'].includes(key)).map(([k,val])=>`${k}: ${typeof val==='object'?JSON.stringify(val):val}`).join('\n');d.audits.unshift({id:id(),name:record.name,userId:userId||'',userName:user?.name||'Demo admin',action,entity,entityId:record.id,timestamp:new Date().toISOString(),before:before?format(before):undefined,after:format(record)});}
function commitData(get:()=>Store,set:(v:Partial<Store>)=>void,fn:(d:Data)=>void){const data=structuredClone(get().data);fn(data);set({data});}
export const useTournament=create<Store>()(persist((set,get)=>({data:createSeed(),userId:null,hydrated:false,storageError:'',
 hydrate:async()=>{if(get().hydrated)return;try{await useTournament.persist.rehydrate();if(!persistedData.safeParse(get().data).success){set({data:createSeed(),userId:null});storageIssue='Saved demo data was damaged or outdated. A fresh demo has been loaded.';}}catch{set({data:createSeed(),userId:null});storageIssue='Saved demo data could not be read. A fresh demo has been loaded.';}try{await refreshRemote();}catch(error){storageIssue=storageIssue||(error as Error).message||'Supabase data is unavailable. Showing the last saved local copy.';}set({hydrated:true,storageError:storageIssue||get().storageError});},
 refresh:async()=>{await refreshRemote();},
 signIn:userId=>{if(!active(get().data.users).some(u=>u.id===userId&&u.active))throw Error('This account is unavailable.');set({userId});},signOut:()=>set({userId:null}),dismissStorageError:()=>set({storageError:''}),reset:()=>set({data:createSeed(),userId:null,storageError:''}),
 save:(entity,record)=>{commitData(get,set,d=>{const before=(d[entity] as RecordItem[]).find(r=>r.id===record.id);const user=authorize(d,get().userId,entity,before||record);if(entity==='events'){const e=record as Data['events'][number];if(!before&&user.role!=='SUPER_ADMIN')throw Error('Only a Super Admin can create events.');if(d.events.some(x=>x.id!==e.id&&x.slug===e.slug))throw Error('This event slug is already in use.');if(e.startDate>e.endDate)throw Error('End date must be on or after start date.');}
 if(entity==='teams'){const t=record as Data['teams'][number];if(!active(d.categories).some(c=>c.id===t.categoryId&&c.eventId===t.eventId))throw Error('Select a category in this event.');if(t.groupId&&!active(d.groups).some(g=>g.id===t.groupId&&g.categoryId===t.categoryId))throw Error('The group must belong to this category.');}
 if(entity==='players'){const p=record as Data['players'][number];if(!active(d.teams).some(t=>t.id===p.teamId&&t.eventId===p.eventId))throw Error('Select a team in this event.');}
 if(entity==='users'&&record.id===get().userId&&(!(record as Data['users'][number]).active||(record as Data['users'][number]).role!=='SUPER_ADMIN'))throw Error('Keep your current Super Admin account active.');
 if(entity==='matches'){const m=record as Match;validateMatch(d,m);if(before&&(before as Match).status==='FINISHED')throw Error('Reopen this finished match before changing participants or schedule.');}
 const rows=d[entity] as RecordItem[];const index=rows.findIndex(r=>r.id===record.id);if(index>=0)rows[index]=record;else rows.push(record);log(d,get().userId,before?'Updated':'Created',entity,record,before);});return queueRemote({action:'save',entity,record});},
 remove:(entity,recordId,permanent=false)=>{commitData(get,set,d=>{const record=(d[entity] as RecordItem[]).find(r=>r.id===recordId);if(!record)throw Error('Record not found.');const user=authorize(d,get().userId,entity,record);if(recordId===get().userId)throw Error('You cannot delete the account you are using.');if(permanent){if(user.role!=='SUPER_ADMIN'||!record.deletedAt)throw Error('Only Super Admins can permanently remove trashed records.');const referenced=Object.values(d).some(rows=>rows.some((r:RecordItem|Data['audits'][number])=>r.id!==recordId&&Object.entries(r).some(([k,v])=>k!=='id'&&k!=='entityId'&&k.endsWith('Id')&&v===recordId)));if(referenced)throw Error('This record is still referenced. Keep it in Trash to preserve tournament history.');}const before=structuredClone(record);
 if(entity==='matches')clearProgression(d,recordId);
 if(['teams','groups','categories','events'].includes(entity))for(const m of d.matches.filter(m=>entity==='teams'?[m.teamAId,m.teamBId].includes(recordId):entity==='groups'?m.groupId===recordId:entity==='categories'?m.categoryId===recordId:m.eventId===recordId))clearProgression(d,m.id);
 if(permanent){const rows=d[entity] as RecordItem[];rows.splice(rows.findIndex(r=>r.id===recordId),1);}else record.deletedAt=new Date().toISOString();log(d,get().userId,permanent?'Permanently deleted':'Moved to Trash',entity,record,before);});void queueRemote({action:'delete',entity,id:recordId,permanent});},
 restore:(entity,recordId)=>{commitData(get,set,d=>{const record=(d[entity] as RecordItem[]).find(r=>r.id===recordId);if(!record)throw Error('Record not found.');authorize(d,get().userId,entity,record);const before=structuredClone(record);delete record.deletedAt;if(entity==='matches'){const m=record as Match;validateMatch(d,m);if(m.status==='FINISHED')updateScore(d,m.id,m.sets,m.status);}log(d,get().userId,'Restored',entity,record,before);});void queueRemote({action:'restore',entity,id:recordId});},
 score:(recordId,sets,status)=>{commitData(get,set,d=>{const old=d.matches.find(m=>m.id===recordId);if(!old)throw Error('Match not found.');const user=authorize(d,get().userId,'matches',old,true);if(user.role==='SCOREKEEPER'&&old.status==='FINISHED')throw Error('An Event Admin must correct finished matches.');const before=structuredClone(old);const m=updateScore(d,recordId,sets,status);log(d,get().userId,status==='FINISHED'?'Published match result':status==='LIVE'?'Updated live match':'Reset / reopened match','matches',m,before);});void queueRemote({action:'score',id:recordId,sets,status});},
 generate:groupId=>{let count=0;const created:Match[]=[];commitData(get,set,d=>{const group=active(d.groups).find(g=>g.id===groupId);if(!group)throw Error('Group not found.');authorize(d,get().userId,'groups',group);const teams=active(d.teams).filter(t=>t.groupId===groupId);for(let a=0;a<teams.length;a++)for(let b=a+1;b<teams.length;b++){if(active(d.matches).some(m=>m.groupId===groupId&&[m.teamAId,m.teamBId].includes(teams[a].id)&&[m.teamAId,m.teamBId].includes(teams[b].id)))continue;for(const lineupCategory of LINEUP_CATEGORIES){const m:Match={id:id(),name:`${teams[a].name} vs ${teams[b].name} · ${lineupCategory}`,eventId:group.eventId,categoryId:group.categoryId,groupId,stage:'GROUP',lineupCategory,teamAId:teams[a].id,teamBId:teams[b].id,status:'SCHEDULED',sets:[]};d.matches.push(m);created.push(m);log(d,get().userId,'Generated match','matches',m);count++;}}});for(const match of created)void queueRemote({action:'save',entity:'matches',record:match});return count;}
}),{name:'pbs-demo-v1',version:1,storage:createJSONStorage(()=>safeStorage),skipHydration:true,partialize:s=>({data:s.data,userId:s.userId}),merge:(saved,current)=>{if(saved===undefined)return current;const p=saved as {data?:unknown;userId?:string|null};if(!persistedData.safeParse(p?.data).success){storageIssue='Saved demo data was damaged or outdated. A fresh demo has been loaded.';return {...current,data:createSeed(),userId:null};}return {...current,data:p.data as Data,userId:typeof p.userId==='string'?p.userId:null};},onRehydrateStorage:()=> (_,error)=>{if(error)storageIssue='Saved demo data could not be read. A fresh demo has been loaded.';}}));
