'use client';
import Link from 'next/link';
import { ArrowUpRight,CalendarDays,MapPin,Trophy,ArrowRight } from 'lucide-react';
import type { Data } from '@/lib/types';
import { dateLabel } from '@/lib/utils';
import { Brand,Empty,Status } from './shared';
export function Home({data}:{data:Data}) {
 const featured=data.events.find(e=>e.status==='ONGOING')||data.events.find(e=>e.status==='UPCOMING')||data.events[0];
 return <><header className="public-header"><Brand/><nav><Link href="/" className="active">Tournaments</Link>{featured&&<Link href={`/e/${featured.slug}/schedule`}>Match centre</Link>}</nav><Link href="/login" className="header-link">Organizer portal <ArrowUpRight size={16}/></Link></header><main className="page"><div className="section-heading"><div><span className="eyebrow">THE GAME BRINGS US TOGETHER</span><h1>The series. The competition.</h1><p>Your courtside companion for every Padel Battle Series event.</p></div><span className="season-tag">2026 SEASON</span></div>{featured?<Link href={`/e/${featured.slug}`} className="feature-event"><div className="feature-copy"><Status value={featured.status}/><span className="eyebrow mt-6">PADEL BATTLE SERIES / 01</span><h2>{featured.name.replace(/\s*\d{4}\s*/,'').toUpperCase()}<span>{featured.startDate.slice(0,4)}<span className="gold">.</span></span></h2><p>Good people. Great padel. Game on.</p><div className="feature-meta"><span><CalendarDays size={17}/>{dateLabel(featured.startDate)} – {dateLabel(featured.endDate)}</span><span><MapPin size={17}/>{featured.venue}</span></div><span className="btn">Explore tournament <ArrowUpRight size={18}/></span></div><div className="court-art" aria-hidden="true">{featured.banner?<img className="feature-banner" src={featured.banner} alt=""/>:<><div className="court-lines"><div/><span className="court-net"/><i/><b/></div><span className="court-label">PADEL BATTLE SERIES<br/>PLAY. BATTLE. BELONG.</span><span className="edition">01 /<br/>{featured.name.toUpperCase()}</span></>}</div></Link>:<Empty title="The next chapter is coming." description="New tournaments will appear here once announced."/>}<div className="section-heading compact"><h2>On the calendar</h2><span className="muted">The next match is always worth it.</span></div><div className="grid-3">{data.events.map((e,i)=><Link href={`/e/${e.slug}`} className="event-card" key={e.id}><div className={`event-art event-art-${i%3}`}><span className="event-number">{String(i+1).padStart(2,'0')}</span><Status value={e.status}/>{e.logo?<img className="event-thumb-logo" src={e.logo} alt=""/>:<Trophy size={54} strokeWidth={1}/>}</div><div className="event-card-body"><span className="eyebrow">PADEL BATTLE SERIES</span><h3>{e.name}<ArrowUpRight size={19}/></h3><p><MapPin size={14}/>{e.venue}</p><div className="event-bottom"><span>{dateLabel(e.startDate)} – {dateLabel(e.endDate)}</span><ArrowRight size={18}/></div></div></Link>)}</div></main><footer className="public-footer"><span>PADEL BATTLE SERIES</span><span>Organized by <strong>A Sportaiment</strong></span><span>© 2026 · Made for the game.</span></footer></>;
}
