'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, CalendarDays, CircleDot, MapPin, Search, SlidersHorizontal, Trophy, X, AlertTriangle } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader } from './ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction } from './ui/alert-dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { dateLabel,timeLabel,titleCase } from '@/lib/utils';
import { active,setWins,standings } from '@/lib/engine';
import type { Data,Event,Match,Team } from '@/lib/types';
export function Brand(){return <Link href="/" className="brand" aria-label="ASPORTAINMENT home"><span className="brand-symbol">A</span><span>ASPORTAINMENT</span></Link>;}
export function Status({value}:{value:string}){return <span className={`badge ${value.toLowerCase()}`}>{['LIVE','ONGOING'].includes(value)&&<span className="status-dot"/>}{titleCase(value)}</span>;}
export function TeamAvatar({team,size=''}:{team?:Team;size?:string}){return <span className={`team-avatar ${size}`} style={{'--team-hue':`${((team?.name.charCodeAt(0)||0)*19)%360}`} as React.CSSProperties}>{team?.logo?<img src={team.logo} alt=""/>:team?.name.split(' ').map(n=>n[0]).slice(0,2).join('')||'?'}</span>;}
export function Empty({title='Nothing here yet',description,action}:{title?:string;description?:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon"><Trophy size={24}/></div><h3>{title}</h3>{description&&<p>{description}</p>}{action}</div>;}
export function Missing(){return <Empty title="This page is out of court." description="The event, team, or match could not be found." action={<Button asChild><Link href="/">Back to events</Link></Button>}/>;}
export function Confirm({open,onOpenChange,title,description,onConfirm,danger=false,permanent=false,label='Confirm',children}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description:string;onConfirm:()=>void;danger?:boolean;permanent?:boolean;label?:string;children?:React.ReactNode}){const [text,setText]=useState('');return <AlertDialog open={open} onOpenChange={v=>{onOpenChange(v);setText('');}}><AlertDialogContent><div className={`confirm-icon ${danger?'danger':''}`}><AlertTriangle size={22}/></div><AlertDialogTitle className="dialog-title">{title}</AlertDialogTitle><AlertDialogDescription className="dialog-description">{description}</AlertDialogDescription>{children}{permanent&&<label className="field">Type DELETE to confirm<Input value={text} onChange={e=>setText(e.target.value)} autoComplete="off"/></label>}<div className="dialog-footer"><AlertDialogCancel className="btn secondary">Cancel</AlertDialogCancel><AlertDialogAction className={`btn ${danger?'danger':''}`} disabled={permanent&&text!=='DELETE'} onClick={onConfirm}>{label}</AlertDialogAction></div></AlertDialogContent></AlertDialog>;}
export function MatchCard({match:m,data:d,event:e,admin=false}:{match:Match;data:Data;event:Event;admin?:boolean}){const a=d.teams.find(t=>t.id===m.teamAId),b=d.teams.find(t=>t.id===m.teamBId),s=setWins(m.sets);return <Link className={`match-card ${m.status==='LIVE'?'is-live':''}`} href={admin?`/admin/events/${e.id}/matches/${m.id}`:`/e/${e.slug}/matches/${m.id}`}><div className="match-card-top"><span>{d.categories.find(c=>c.id===m.categoryId)?.name} <span className="dot-separator">·</span> {d.groups.find(g=>g.id===m.groupId)?.name||titleCase(m.stage)}</span><Status value={m.status}/></div><div className={`match-team ${m.winnerId===a?.id?'winner':''}`}><TeamAvatar team={a}/><span>{a?.name||'To be decided'}</span>{m.sets.length>0&&<strong>{m.status==='FINISHED'?s.a:m.sets.at(-1)?.a}</strong>}</div><div className={`match-team ${m.winnerId===b?.id?'winner':''}`}><TeamAvatar team={b}/><span>{b?.name||'To be decided'}</span>{m.sets.length>0&&<strong>{m.status==='FINISHED'?s.b:m.sets.at(-1)?.b}</strong>}</div><div className="match-card-bottom"><span><CircleDot size={13}/>{d.courts.find(c=>c.id===m.courtId)?.name||'Court TBC'}</span><span>{m.status==='FINISHED'?m.sets.map(s=>`${s.a}–${s.b}`).join(' / '):timeLabel(m.scheduledAt)}<ArrowRight size={14}/></span></div></Link>;}
export function StandingsTable({data,groupId,slug,compact=false}:{data:Data;groupId:string;slug:string;compact?:boolean}){const rows=standings(data,groupId);if(!rows.some(r=>r.MP))return <Empty title="The table is waiting." description="Standings will appear after the first completed match."/>;const columns=['W','L','SF','SA','SD','GF','GA','GD'] as const;return <div className={`standings-wrap ${compact?'standings-compact':''}`}><table className="standings-table"><thead><tr><th>POS</th><th>TEAM</th>{columns.map(c=><th key={c} className={['SF','SA','GF','GA','GD'].includes(c)?'stat-extra':''}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.team.id} className={i<2?'qualifying':''}><td><span className="position">{i+1}</span></td><td><Link className="table-team" href={`/e/${slug}/teams/${r.team.id}`}><TeamAvatar team={r.team}/><span>{r.team.name}{r.tied&&<small className="tie-note">Tie needs review</small>}</span></Link></td>{columns.map(c=><td key={c} className={['SF','SA','GF','GA','GD'].includes(c)?'stat-extra':''}>{r[c]>0&&['SD','GD'].includes(c)?'+':''}{r[c]}</td>)}</tr>)}</tbody></table>{compact&&<div className="mobile-standings">{rows.map((r,i)=><Link key={r.team.id} href={`/e/${slug}/teams/${r.team.id}`}><span className="position">{i+1}</span><TeamAvatar team={r.team}/><div><strong>{r.team.name}</strong><small>W {r.W} · L {r.L} · SD {r.SD>0?'+':''}{r.SD}{r.tied?' · Tie needs review':''}</small></div></Link>)}</div>}</div>;}
export interface FilterSpec {key:string;label:string;options:{value:string;label:string}[];}
export function FilterBar({search,onSearch,filters,values,onChange,children}:{search:string;onSearch:(v:string)=>void;filters:FilterSpec[];values:Record<string,string>;onChange:(key:string,value:string)=>void;children?:React.ReactNode}){const [open,setOpen]=useState(false);const selects=<>{filters.map(f=><label key={f.key} className="filter-select"><span className="sr-only">{f.label}</span><select aria-label={f.label} value={values[f.key]||''} onChange={e=>onChange(f.key,e.target.value)}><option value="">All {f.label.toLowerCase()}</option>{f.options.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select></label>)}</>;const chosen=filters.filter(f=>values[f.key]);return <><div className="filter-bar"><label className="search-input"><Search size={17}/><input placeholder="Search…" aria-label="Search" value={search} onChange={e=>onSearch(e.target.value)}/>{search&&<button onClick={()=>onSearch('')} aria-label="Clear search"><X size={15}/></button>}</label><div className="desktop-filters">{selects}</div><Button className="mobile-filter-toggle" variant="secondary" onClick={()=>setOpen(true)}><SlidersHorizontal size={16}/>Filters {chosen.length>0&&`(${chosen.length})`}</Button>{children}</div>{chosen.length>0&&<div className="filter-chips">{chosen.map(f=><button key={f.key} onClick={()=>onChange(f.key,'')}>{f.options.find(o=>o.value===values[f.key])?.label||values[f.key]}<X size={12}/></button>)}<button onClick={()=>filters.forEach(f=>onChange(f.key,''))}>Clear filters</button></div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="filter-sheet"><DialogHeader><DialogTitle>Filter results</DialogTitle><DialogDescription>Narrow down the matches and teams you want to see.</DialogDescription></DialogHeader><div className="filter-sheet-fields">{selects}</div><Button onClick={()=>setOpen(false)}>Show results</Button></DialogContent></Dialog></>;}
export const options=(items:{id:string;name:string;deletedAt?:string}[])=>active(items).map(i=>({value:i.id,label:i.name}));
export function EventMeta({event}:{event:Event}){return <div className="feature-meta"><span><CalendarDays size={16}/>{dateLabel(event.startDate)} – {dateLabel(event.endDate,{year:'numeric'})}</span><span><MapPin size={16}/>{event.venue}</span></div>;}
